name: This is a great start of our project
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Check if yarn fix has ben run
      run: |
        ls
        cd ..
        ls
        yarn install
        yarn fix --silent
        git add.
        if git diff --quiet; then echo "No changes after running yarn fix"; else echo "Changes detected after running yarn fix"; exit 1; fi